import type { Character, Episode } from "./schemas";

export const demoCharacters: Character[] = [
  {
    id: "pip",
    name: "Pip",
    role: "Inventor & optimist",
    personality: "Curious, quick-thinking, and delighted by every near-disaster.",
    appearance: "Warm brown skin, expressive brown eyes, and two round puff ponytails.",
    wardrobe: "Teal utility jacket, mustard shirt, navy shorts, orange high-tops, amber goggles.",
    proportions: "Stylized 3D child proportions, oversized head and hands, compact silhouette.",
    voiceName: "Maya — bright, warm",
    voiceId: "preset_maya",
    referenceUrl: "/demo/pip-moss-reference.png",
    approved: true,
  },
  {
    id: "moss",
    name: "Moss",
    role: "Robot sidekick",
    personality: "Methodical, literal, and secretly thrilled by adventure.",
    appearance: "Mint-and-cream robot with amber LED eyes and one flexible antenna.",
    wardrobe: "Integrated cream shell with teal panels and a glowing amber chest light.",
    proportions: "Small rounded body, wide feet, soft rectangular screen face.",
    voiceName: "Quinn — gentle, precise",
    voiceId: "preset_quinn",
    referenceUrl: "/demo/pip-moss-reference.png",
    approved: true,
  },
];

export const demoEpisode: Episode = {
  id: "the-cloud-in-a-jar",
  seriesId: "pip-and-moss",
  title: "The Cloud in a Jar",
  number: 4,
  logline: "Pip tests a pocket weather machine, and Moss discovers that forecasts can have feelings.",
  recap:
    "Pip and Moss rebuilt their rooftop workshop after the kite parade. Moss is still learning when a careful plan needs a playful exception.",
  aspectRatio: "16:9",
  targetDurationSeconds: 42,
  scenes: [
    {
      id: "scene-1",
      position: 0,
      title: "A tiny forecast",
      characters: ["Pip", "Moss"],
      setting: "Rooftop workshop at blue hour",
      action: "Pip turns the brass dial. A tiny storm cloud appears and rains exactly one drop onto Moss's umbrella.",
      dialogue: "Pip: One cloud, pocket-sized. Moss: Probability of indoor weather was previously zero.",
      camera: "Slow push-in from workbench height",
      targetDurationSeconds: 12,
      audioDurationSeconds: 11.4,
      status: "approved",
      approved: true,
      frameUrl: "/demo/weather-workshop.png",
      voiceId: "preset_maya",
      captionsEnabled: true,
      creditEstimate: 18,
      words: [
        { word: "One", startSeconds: 0.3, endSeconds: 0.6 },
        { word: "cloud,", startSeconds: 0.6, endSeconds: 1.1 },
        { word: "pocket-sized.", startSeconds: 1.1, endSeconds: 2.2 },
      ],
    },
    {
      id: "scene-2",
      position: 1,
      title: "The breeze gets ideas",
      characters: ["Pip", "Moss"],
      setting: "Workshop rooftop, moments later",
      action: "A ribbon of teal wind circles Pip and Moss, lifting the plans from the workbench.",
      dialogue: "Pip: Okay, that's more weather than pocket. Moss: Updating forecast: hold onto your goggles.",
      camera: "Wide orbit with a gentle clockwise move",
      targetDurationSeconds: 14,
      audioDurationSeconds: 13.1,
      status: "frame_ready",
      approved: false,
      frameUrl: "/demo/windy-rooftop.png",
      voiceId: "preset_quinn",
      captionsEnabled: true,
      creditEstimate: 18,
      words: [
        { word: "Updating", startSeconds: 4.8, endSeconds: 5.5 },
        { word: "forecast:", startSeconds: 5.5, endSeconds: 6.2 },
        { word: "hold", startSeconds: 6.2, endSeconds: 6.7 },
      ],
    },
    {
      id: "scene-3",
      position: 2,
      title: "A gentler setting",
      characters: ["Pip", "Moss"],
      setting: "Rooftop under calm string lights",
      action: "Moss taps the smallest dial. The wind settles into a breeze that spins one paper pinwheel.",
      dialogue: "Moss: Forecast revised. Pip: Perfectly imperfect.",
      camera: "Medium two-shot, then rack focus to the pinwheel",
      targetDurationSeconds: 11,
      audioDurationSeconds: 9.8,
      status: "draft",
      approved: false,
      frameUrl: "/demo/weather-workshop.png",
      voiceId: "preset_quinn",
      captionsEnabled: true,
      creditEstimate: 18,
      words: [],
    },
  ],
};

export const demoSeriesGuide = {
  title: "Pip & Moss",
  visualStyle: "Tactile 3D cartoon with cinematic lighting and handcrafted workshop details.",
  palette: ["#22d3a5", "#ffb454", "#ff7c6d", "#17211f"],
  locations: ["Rooftop workshop", "Juniper Street", "Community greenhouse"],
  relationship: "Pip improvises; Moss measures. Both learn from the other.",
  continuity: [
    "Pip keeps her amber goggles on her head unless a machine sparks.",
    "Moss's antenna bends with emotion but never detaches.",
    "The star tool pouch was a gift from Pip's grandmother.",
  ],
};
