import Link from "next/link";
import { MarketingPage } from "@/components/marketing/site-chrome";
import { JsonLd } from "@/components/marketing/json-ld";
import { publicMetadata } from "@/lib/seo/metadata";
import { pageSchema, breadcrumbSchema, organizationId } from "@/lib/seo/structured-data";

const title = "About ETA — AI Video Creation Studio";
const description = "Learn what ETA creates: narrated faceless videos and character-led AI cartoons, with editable planning, credit estimates and private video downloads.";
export const metadata = publicMetadata({ title, description, path: "/about" });

export default function AboutPage() {
  return <MarketingPage title="A creative studio for ideas worth sharing." description="ETA is a web-based AI video creation studio. It helps creators, educators and small teams turn a topic, script or character image into a short video without filming themselves." eyebrow="About ETA">
    <JsonLd data={{ ...pageSchema("/about", title, description, "AboutPage"), about: { "@id": organizationId } }} />
    <JsonLd data={breadcrumbSchema([{ name: "Home", path: "/" }, { name: "About ETA", path: "/about" }])} />
    <section className="max-w-3xl"><h2 className="editorial text-3xl">Two different ways to tell a story</h2><p className="mt-4 leading-8 text-muted-foreground">The <Link href="/features/faceless-video-generator" className="text-primary underline">faceless video generator</Link> combines an editable script, AI still images, narration and optional timed captions. It is intended for narrated explanations and short stories. It does not generate moving footage for every scene.</p><p className="mt-4 leading-8 text-muted-foreground">The <Link href="/features/ai-cartoon-series" className="text-primary underline">AI cartoon studio</Link> creates a cast and editable storyboard before generating character-led animation. You can start with a prompt or reference artwork and review actions and dialogue before paying for animation. The finished output is a video, not an editable 3D model or character rig.</p></section>
    <section className="max-w-3xl"><h2 className="editorial text-3xl">You review the plan before rendering</h2><p className="mt-4 leading-8 text-muted-foreground">Generation is organized into visible stages. Review the story, change supported scene details and check the credit estimate before starting the next stage. Jobs run in the background, so you can return to a saved project to check progress and download its completed video.</p><p className="mt-4 leading-8 text-muted-foreground">An AI model can make mistakes. Generated characters can drift between scenes; spoken words and lip sync can vary; factual narration needs a human check. ETA describes these limitations on the relevant feature pages. Illustrative artwork is labeled as an illustration rather than presented as proof of a completed customer generation.</p></section>
    <section className="max-w-3xl"><h2 className="editorial text-3xl">Practical information, without the guesswork</h2><p className="mt-4 leading-8 text-muted-foreground">The public <Link href="/pricing" className="text-primary underline">pricing page</Link> explains monthly and annual billing, credit budgets and generation failures. Our <Link href="/guides/faceless-videos-vs-ai-cartoons" className="text-primary underline">workflow comparison</Link> helps you choose between narration-led videos and cartoons. These pages describe the current product rather than treating roadmap ideas as released features.</p><p className="mt-4 leading-8 text-muted-foreground">Projects and generated media are managed through your signed-in workspace. If you need help with a stuck job, billing or an account, use the <Link href="/contact" className="text-primary underline">support page</Link>. Do not include passwords, API keys or payment-card details in your message. We can review a reported product limitation or an inaccurate description when you identify the relevant page or job.</p></section>
  </MarketingPage>;
}
