import { beforeEach,describe,it,expect,vi } from "vitest";
const mocks=vi.hoisted(()=>({requireAccount:vi.fn(),passwordVerify:vi.fn(),passwordUpdate:vi.fn(),signOut:vi.fn(),portal:vi.fn(),subscriptions:vi.fn()}));
vi.mock("next/cache",()=>({revalidatePath:vi.fn()}));
vi.mock("@/lib/account",()=>({requireAccount:mocks.requireAccount,publicError:(error:unknown)=>error instanceof Error?error.message:"Failed"}));
vi.mock("@/lib/billing/stripe",()=>({accountReturnUrl:()=>"https://studio.test/studio/profile",getBillingCustomer:vi.fn(),getStripe:()=>({subscriptions:{list:mocks.subscriptions},billingPortal:{sessions:{create:mocks.portal}}})}));
import { changePassword,openBillingPortal } from "@/app/studio/profile/actions";
beforeEach(()=>{vi.clearAllMocks();mocks.passwordVerify.mockResolvedValue({error:null});mocks.passwordUpdate.mockResolvedValue({error:null});mocks.signOut.mockResolvedValue({error:null});mocks.subscriptions.mockResolvedValue({data:[{id:"sub_owned",status:"active"}]});mocks.portal.mockResolvedValue({url:"https://billing.stripe.com/session/test"});const chain={select:()=>chain,eq:()=>chain,maybeSingle:async()=>({data:{stripe_customer_id:"cus_owned"},error:null})};mocks.requireAccount.mockResolvedValue({user:{id:"owner",email:"creator@example.test"},admin:{from:()=>chain},db:{auth:{signInWithPassword:mocks.passwordVerify,updateUser:mocks.passwordUpdate,signOut:mocks.signOut}}});});
describe("authenticated profile and billing actions",()=>{
  it("requires the current password before updating credentials",async()=>{mocks.passwordVerify.mockResolvedValue({error:{message:"wrong"}});const result=await changePassword({currentPassword:"wrong",password:"new-secure-password",confirmation:"new-secure-password"});expect(result.error).toContain("Current password");expect(mocks.passwordUpdate).not.toHaveBeenCalled();});
  it("updates a verified password and revokes other sessions",async()=>{expect(await changePassword({currentPassword:"old-password",password:"new-secure-password",confirmation:"new-secure-password"})).toEqual({ok:true});expect(mocks.passwordUpdate).toHaveBeenCalledWith({password:"new-secure-password"});expect(mocks.signOut).toHaveBeenCalledWith({scope:"others"});});
  it("rejects mismatched passwords without touching the provider",async()=>{expect((await changePassword({currentPassword:"old",password:"new-secure-password",confirmation:"different-password"})).error).toBeTruthy();expect(mocks.passwordVerify).not.toHaveBeenCalled();});
  it("opens card updates only for the authenticated customer's mapping",async()=>{expect((await openBillingPortal("payment")).url).toContain("billing.stripe.com");expect(mocks.portal).toHaveBeenCalledWith(expect.objectContaining({customer:"cus_owned",flow_data:expect.objectContaining({type:"payment_method_update"})}));});
  it("uses Stripe's confirmation flow for owned subscription cancellation",async()=>{await openBillingPortal("cancel");expect(mocks.subscriptions).toHaveBeenCalledWith(expect.objectContaining({customer:"cus_owned"}));expect(mocks.portal).toHaveBeenCalledWith(expect.objectContaining({customer:"cus_owned",flow_data:expect.objectContaining({type:"subscription_cancel",subscription_cancel:{subscription:"sub_owned"}})}));});
  it("does not open billing for unauthenticated requests",async()=>{mocks.requireAccount.mockRejectedValue(new Error("Please sign in"));expect((await openBillingPortal("manage")).error).toBe("Please sign in");expect(mocks.portal).not.toHaveBeenCalled();});
});
