import Link from "next/link";
import { MarketingPage } from "@/components/marketing/site-chrome";
import { JsonLd } from "@/components/marketing/json-ld";
import { publicMetadata } from "@/lib/seo/metadata";
import { comparisonRows } from "@/lib/seo/editorial-content";
import { absoluteUrl, breadcrumbSchema, organizationId } from "@/lib/seo/structured-data";

const path = "/guides/faceless-videos-vs-ai-cartoons";
const title = "Faceless Videos vs AI Cartoons: Which Should You Create?";
const description = "Compare ETA's faceless video and AI cartoon workflows: still images versus animation, narration versus dialogue, review steps, formats and limitations.";
export const metadata = publicMetadata({ title, description, path });

export default function ComparisonGuide() {
  return <MarketingPage title="Faceless videos or AI cartoons? Start with the story." description="Choose a faceless video when narration carries the idea. Choose an AI cartoon when characters, actions and spoken dialogue are central. In ETA, the first uses AI still images; the second generates moving character-led scenes." eyebrow="ETA workflow guide">
    <JsonLd data={{ "@context": "https://schema.org", "@type": "Article", headline: title, description, mainEntityOfPage: absoluteUrl(path), image: absoluteUrl("/opengraph-image"), author: { "@type": "Organization", "@id": organizationId, name: "ETA", url: absoluteUrl("/about") }, publisher: { "@id": organizationId }, datePublished: "2026-09-25", dateModified: "2026-09-25", inLanguage: "en" }} />
    <JsonLd data={breadcrumbSchema([{ name: "Home", path: "/" }, { name: "Guides", path: "/guides" }, { name: "Faceless videos vs AI cartoons", path }])} />
    <p className="text-sm text-muted-foreground">By <Link href="/about" className="underline">ETA</Link> · Updated <time dateTime="2026-09-25">September 25, 2026</time> · Based on the current ETA workflows</p>
    <section><h2 className="editorial text-3xl">What is the difference?</h2><p className="mt-4 max-w-3xl leading-8 text-muted-foreground">A faceless video is a video made without the creator appearing on camera. That describes a presentation style, not a single production technique. ETA’s faceless tool specifically combines AI-generated still images with a narration track and optional timed captions. A cartoon uses animated characters and scene actions to carry the story. ETA’s cartoon tool first produces character references and an editable story, then sends the approved scene instructions to an animation model.</p><div className="mt-7 overflow-x-auto rounded-xl border border-border"><table className="w-full min-w-[650px] text-left text-sm"><caption className="sr-only">Current ETA faceless video and cartoon capabilities</caption><thead className="bg-accent/50"><tr><th scope="col" className="p-4">Production choice</th><th scope="col" className="p-4">Faceless video</th><th scope="col" className="p-4">AI cartoon</th></tr></thead><tbody>{comparisonRows.map((row) => <tr className="border-t border-border" key={row.label}><th scope="row" className="p-4 align-top">{row.label}</th><td className="p-4 align-top leading-6">{row.faceless}</td><td className="p-4 align-top leading-6">{row.cartoons}</td></tr>)}</tbody></table></div></section>
    <section className="grid gap-10 md:grid-cols-2"><div><h2 className="editorial text-3xl">When should you choose a faceless video?</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Use the narration-led workflow for a short explanation, a lesson introduction or a story told by a narrator. Start with your own script if exact phrasing matters, or use an idea to request an AI draft. Review claims, names and pronunciation before rendering. Visual prompts should support the spoken explanation, not introduce a second unrelated story.</p><p className="mt-4 text-sm leading-7 text-muted-foreground">This is also the simpler choice when you do not need a recurring animated cast. It is not the right fit if you expect full-motion character acting, stock footage selection or automatic publishing to a social account.</p><Link href="/features/faceless-video-generator" className="mt-4 inline-block text-sm text-primary underline">See faceless video capabilities</Link></div><div><h2 className="editorial text-3xl">When should you choose a cartoon?</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Choose a cartoon when an action or exchange between characters is the point of the video: a small visual joke, a short fictional scene or a character explaining an idea through dialogue. Describe appearance, setting and one clear action per scene. Use your own reference artwork only when you have permission to use it.</p><p className="mt-4 text-sm leading-7 text-muted-foreground">Review the cast before buying animation. AI-generated movement, exact dialogue and character continuity can vary. The reference-guided workflow helps establish a cast, but it is not a guarantee that every detail stays identical across all frames.</p><Link href="/features/ai-cartoon-series" className="mt-4 inline-block text-sm text-primary underline">See cartoon creation capabilities</Link></div></section>
    <section><h2 className="editorial text-3xl">How can you write a useful first brief?</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">State the audience, one idea, the tone and the desired format. Separate narration from what the viewer should see. For animation, include the character’s motivation and a simple sequence of actions. Avoid asking one short scene to change locations, introduce many people and deliver several paragraphs of dialogue.</p><div className="mt-6 grid gap-6 md:grid-cols-2"><div className="rounded-xl border border-border bg-card p-6"><h3 className="font-semibold">Example faceless brief</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">Create a 30-second vertical explainer for new gardeners about checking soil before watering. Use three clear scenes, a calm English narrator, watercolor-style images and readable captions. End with one practical reminder.</p></div><div className="rounded-xl border border-border bg-card p-6"><h3 className="font-semibold">Example cartoon brief</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">Create a 15-second cartoon about a curious orange cat discovering a toy robot in a sunny workshop. The cat taps it, the robot wakes up and says one short friendly line, and the cat jumps back in surprise. Keep the setting and character designs consistent.</p></div></div><p className="mt-3 text-xs text-muted-foreground">These are illustrative prompt examples, not claims about a generated result.</p></section>
    <section><h2 className="editorial text-3xl">What should you review before sharing?</h2><ul className="mt-5 list-disc space-y-3 pl-5 text-sm leading-7 text-muted-foreground"><li>Check every factual statement and any spoken names. AI output is not a source of verified facts.</li><li>Watch for character changes, distorted objects and dialogue that differs from your storyboard.</li><li>Check caption legibility when captions are available, especially on a phone screen.</li><li>Confirm that your images, character designs and publishing use comply with the rights and permissions that apply to them.</li><li>Choose the output orientation before generation and check the completed file before uploading it anywhere else.</li></ul><p className="mt-6 text-sm leading-7 text-muted-foreground">Both workflows use credits. Costs depend on the generation stage and, for cartoons, the chosen duration and model. Review the estimate shown in the studio and see <Link className="text-primary underline" href="/pricing">pricing and credits</Link>. Neither workflow currently auto-posts your video to social platforms.</p></section>
  </MarketingPage>;
}
