import { FILM_PLAN_CREDITS, filmModelIds, filmRenderCredits } from "./models";

export const filmEditorial = {
  updatedAt: "2026-10-03T00:00:00.000Z",
  summary: "An AI short film generator turns a story idea into connected scenes, rather than asking you to assemble unrelated video prompts. ETA gives you a focused production path: describe a small story, approve the cast and written shot plan, then generate opening frames and motion with a selected fal model. Choose 24, 48, 60, 120 or 180 seconds. ETA automatically assembles connected six- and eight-second shots; three minutes is a directed multi-shot production, not a single model call. The structure works best when the audience can understand the protagonist, the change and the ending without a long explanation. You remain the director: the story, camera movement, action and spoken lines can all be reviewed before the final render.",
  steps: [
    { title: "Write one achievable story", text: "Start with a protagonist, a location and a change. For example: a lighthouse keeper discovers a light inside a broken lantern and carries it upstairs to relight the tower. This gives the film a beginning, movement and resolution. A small cast and a stable setting make it easier to maintain visual continuity. Choose landscape for a conventional film frame or vertical for a mobile-first story. Pick a visual look such as cinematic realism, noir, science fiction, fantasy, anime or 3D animation." },
    { title: "Choose a model without learning every API", text: `Use Character story for a reference-led Kling O3 production, Budget first pass for MiniMax H3 Max Turbo, or Detailed scenes for Veo 3.1. The advanced panel exposes ${filmModelIds.length} integrated fal endpoints across several model families. Your estimate updates when you change the model or runtime. These presets are workflow recommendations, not a benchmark or a promise that one model always looks better. Different models interpret faces, movement, lighting and speech differently; start with a shorter film to evaluate the fit.` },
    { title: "Review the cast and direct each shot", text: "The planning stage writes a title, synopsis, fixed cast descriptions, a story-and-world bible and a shot-by-shot continuity chain. It also creates character portraits. You may supply up to three character reference images when you have the necessary rights and likeness consent. The cast is locked after planning so the production has a stable identity reference. At the director’s desk, edit each scene’s setting, action, camera direction, sound and dialogue, and review the story state entering and leaving each shot. Continuity-guided plans keep shot order fixed. Keep dialogue brief enough to finish within the shot. This is a written storyboard with cast portraits, not a visual timeline editor." },
    { title: "Generate, review and download", text: "Approve the render only after the story reads clearly. ETA creates an opening frame for each shot using the approved cast and world bible. Repeated locations reuse their original frame; continuous shots also reference the preceding shot’s final frame. The selected video model receives this frame and shot direction. Kling variants also receive character elements. The worker normalizes and assembles the clips into one private MP4. Choose native dialogue and ambience or a silent export. Rendering continues in the background; return through Projects or Jobs to see progress. Watch the whole film before sharing it, especially faces, hands, spoken words and the transitions between scenes." },
  ],
  useCases: [
    { title: "Narrative experiments", text: "Test a complete miniature story before investing in a larger production. A lost object, an unexpected visitor or a small act of kindness can produce a readable emotional arc in three shots. Use up to three minutes when the plot genuinely needs more space. Preserve a clear setup, escalation and payoff rather than repeating establishing shots." },
    { title: "Mood and concept films", text: "Explore the atmosphere of a fictional world with a consistent cast and visual direction. Specify lighting, materials and restrained camera movement rather than stacking many conflicting style terms. The output can be useful for discussing a concept, but it is generated footage, not evidence that a real location, person or event was filmed." },
    { title: "Vertical visual stories", text: "Build a short, self-contained story for a mobile audience. Select vertical framing before planning, keep the main action readable and avoid tiny background details. The final MP4 can be downloaded for editing or publishing. This workflow does not automatically add captions, licensed music or a platform-specific marketing strategy." },
  ],
  faqs: [
    { question: "Which AI model should I use for a short film?", answer: "Start with Kling O3 when recurring characters matter because the workflow supplies both an opening frame and character references. MiniMax H3 Max Turbo is a lower-credit starting point. Veo 3.1 is another option for detailed scenes. Seedance, Grok, Wan, Happy Horse, LTX, PixVerse and Gemini Omni are available in advanced settings. Model access and behavior can change; no universal quality ranking or guaranteed result is claimed." },
    { question: "Can I generate a three-minute film from one idea?", answer: "Yes. Select 180 seconds and describe the story. ETA plans 23 linked shots, creates cast and location references, carries story state between shots, and assembles the MP4 automatically. You approve planning and rendering separately. You do not need to stitch clips yourself. This is not a single uninterrupted 180-second model generation, and visual or voice consistency can still vary." },
    { question: "How much does a complete short film cost?", answer: `Planning and cast portraits cost ${FILM_PLAN_CREDITS} ETA credits. A 24-second Kling O3 film render costs ${filmRenderCredits("film-kling-o3",24)} credits, including its opening frames, for ${FILM_PLAN_CREDITS+filmRenderCredits("film-kling-o3",24)} credits across both stages. The live form shows other combinations before you confirm. Each re-render is charged separately. Completed planning remains charged if you stop there; failed or cancelled stages return their reserved credits. These are ETA credit prices, not fal’s dollar prices.` },
    { question: "Will my characters and voices stay identical?", answer: "Reference portraits, fixed wardrobe descriptions and image-guided shots help continuity, but identity, hands, voices, exact dialogue and lip sync can still vary. Keep the cast small and the action simple. Voices are generated by the video model; this feature does not clone a voice or guarantee one voice identity across every shot." },
    { question: "Can I upload my own actor or character image?", answer: "Yes. Upload up to three JPG, PNG or WebP images, up to 8 MB each, with one clearly visible character per image. Use original characters or adult likenesses with permission for this use. You must also have the necessary rights to your story and other material. Do not use the feature to impersonate people or fabricate endorsements." },
    { question: "What resolution and audio will I receive?", answer: "The selected model’s export setting is shown before creation: 720p, 768p or 1080p. Clips are normalized to a consistent canvas and 24 frames per second, then assembled into an MP4. An export resolution is not a claim that every source was generated natively at that size. Native sound can include dialogue, ambience and effects, but it is not a separately editable sound mix. Silent exports remove sound; some models still generate it internally at the same price." },
    { question: "Is this the same as the AI cartoon generator?", answer: "Both workflows use cast planning and private background rendering, but Short Film is designed for cinematic stories with a continuity-guided structure of up to 23 shots and a wider image-guided model catalog. Cartoon Studio offers its own animation styles, durations and direct-prompt options. Choose the workflow that matches the production you want to make, and review its separate credit estimate." },
  ],
};
