export const estateEditorial = {
  updatedAt: "2026-10-04T00:00:00.000Z",
  summary: "ETA’s real estate video generator turns your own listing photos into an ordered property video, rather than inventing a house from a text prompt. Upload two to twelve photos, name each space, choose six or eight seconds per room, and add an agent contact card. Faithful photo motion uses your actual images without generative changes. Optional AI models create camera motion from each source photo, with a visible disclosure and a required human review. The result is a private landscape or portrait MP4, with optional English voiceover and a separate room-timed SRT caption file. Nothing is automatically published to a listing portal or social account.",
  steps: [
    { title: "Choose photos that explain the property", text: "Start with a clear exterior or the strongest living space. Follow with the kitchen, bedrooms, bathrooms and any verified outdoor features. Upload JPEG, PNG or WebP images, each no larger than 8 MB. Use images you have permission to publish, with at least 256 pixels on each side and no more than 20 megapixels. Avoid near-duplicate angles, embedded watermarks and photos that reveal private paperwork, security codes or people who have not agreed to appear. The original photos remain available inside the project for comparison with the finished tour." },
    { title: "Arrange a believable room sequence", text: "Use the up and down controls to arrange the property tour. Each room has an editable label, an optional short caption or narration line, and a gentle push, subtle pan or still-camera setting. The sequence is editorial: separate photographs do not prove rooms connect physically. Do not describe the result as a measured floor plan or an interactive walkthrough. Keep price, address and amenity claims accurate and current. ETA does not verify listing information, invent missing property details or import an MLS listing automatically." },
    { title: "Choose faithful motion or an AI engine", text: "Faithful photo motion is the conservative starting point for factual listing marketing. It animates the supplied images without asking a model to redesign the space. For generated motion, choose Kling 3.0 Pro or Standard, Seedance 2.5, Veo 3.1 or Fast, Wan 3.0, or LTX 2.3 Pro or Fast. These are image-guided fal integrations, not a promise that any model will preserve architecture perfectly. Restrained movement often gives a more usable result than a dramatic fly-through. Every AI export carries a disclosure; compare windows, doors, furniture and exterior views against your originals." },
    { title: "Review the script, branding and cost", text: "Add an agent or agency name, contact information, a brand color and a final call to action such as Book a viewing. Optional ElevenLabs v3 narration speaks your approved English room text using Rachel or Aria. Keep each line within eleven words for a six-second room or fifteen words for an eight-second room; unusually slow speech can still exceed the slot, in which case the render fails instead of cutting off words. Saving the listing is free. The separate render confirmation shows the complete credit reservation before work begins. Saved briefs are locked; create a new listing if the details need changing." },
    { title: "Download, inspect and share deliberately", text: "After rendering, download the MP4 and optional SRT file from the saved project. Landscape exports use a 1920 by 1080 canvas; portrait exports use 1080 by 1920. Images and clips are fitted with padding rather than forcibly cropped to fill a different shape. The export canvas does not turn lower-resolution source material into native high-resolution footage. Watch the full video with sound, inspect contact text and compare every generated room with the original photo. Only publish after checking the rules and disclosure requirements of your destination. ETA does not provide a guarantee of MLS acceptance or advertising compliance." },
  ],
  useCases: [
    { title: "A focused social listing teaser", text: "Choose four or five strong photos in portrait format, keep the camera motion modest and end with one clear contact action. A four-photo tour using six-second rooms plus the contact card lasts twenty-eight seconds. Make room labels readable on a phone, and put the most useful factual information first. The original image remains fully visible even when its aspect ratio differs from the portrait canvas." },
    { title: "A landscape property overview", text: "Use landscape format for a property website, presentation or a manually uploaded video. Six to twelve photos can give each major space attention without repeating the same view. A twelve-photo tour with eight-second rooms and the four-second contact card lasts one hundred seconds. This is an edited photo-based tour, not a replacement for an in-person viewing, a survey or captured walkthrough footage." },
    { title: "A branded agency workflow", text: "Keep the same agent name, contact details and brand color across listing projects. Use faithful motion for an accurate first pass, then decide whether a new AI-motion version is worth the extra credits. Each project stores the reviewed photo order and selected settings. Private, expiring download links make it possible to return to an export without putting every source image on a public portfolio." },
  ],
  faqs: [
    { question: "How much does a real estate video cost in ETA credits?", answer: "The cost is ten export credits plus the number of photos multiplied by seconds per room and the selected engine’s rate. Faithful photo motion costs one credit per room-second. AI rates range from five to eighty credits per room-second. Optional narration adds five credits per room. For example, four six-second photos cost thirty-four credits in silent faithful mode, or fifty-four with narration. The studio displays the exact total; these are ETA credit rates, not quoted provider dollar prices." },
    { question: "Which model gives the best real estate video?", answer: "There is no verified universal winner. Source-photo quality, camera motion and the room itself affect results. Faithful photo motion avoids generative changes and is the recommended starting point when accuracy matters most. LTX 2.3 Fast is a lower-credit AI option for exploration; the other engines offer alternative motion styles at different costs. ETA has verified the integrations against fal’s published API contracts, not established a paid, controlled image-quality ranking." },
    { question: "Can AI change the property’s appearance?", answer: "Yes. Even when prompted to preserve a supplied photograph, a video model may distort architecture or add, remove or move objects. AI-generated clips are labelled and should be checked against the originals. Use faithful photo motion if you do not want generative changes. Neither mode should be used to conceal defects or misrepresent a property, and ETA does not automatically detect every visual change." },
    { question: "Are music, captions and a continuous walkthrough included?", answer: "The current workflow supports optional English narration and a separate SRT file timed to each room. Captions are not burned into the video. It does not include background music, virtual staging, a continuous room-to-room walkthrough, an interactive 3D tour or automatic portal publishing. The clips are assembled into one MP4 in the order you approve, with a four-second branded contact card." },
    { question: "What happens if a render is interrupted?", answer: "Room artifacts and confirmed provider request IDs are checkpointed. A retry resumes known work instead of intentionally submitting it again. An uncertain paid submission is stopped for investigation rather than blindly repeated. Follow progress in the project or Jobs, and request cancellation there. Failed or confirmed cancelled listing renders return their reserved credits. Cancellation can take time when external work is already running." },
  ],
};
