"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { CancelJobButton } from "./cancel-job-button";
import { startAdRemakeJob } from "@/app/studio/ad-remake/actions";
import { adRemakeCredits, adRemakeModels, type AdRemakeProject } from "@/lib/ad-remake/schema";

export function AdRemakeReview({ project: p }: { project: AdRemakeProject }) {
  const router = useRouter(), [pending, startTransition] = useTransition(), [approved, setApproved] = useState(false), [error, setError] = useState<string | null>(null);
  const active = p.status === "rendering";
  useEffect(() => { if (!active) return; const timer = setInterval(() => { if (!document.hidden) router.refresh(); }, 6000); return () => clearInterval(timer); }, [active, router]);
  return <main className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><Link href="/studio/ad-remake" className="text-sm text-primary">← Ad Remake studio</Link><p className="eyebrow mt-8 text-primary">Ad Remake / Review & render</p><h1 className="editorial mt-3 text-4xl">{p.title}</h1>
    <div className="mt-8 grid items-start gap-7 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-7"><section className="grid gap-4 sm:grid-cols-2"><div><h2 className="mb-3 font-semibold">Original reference</h2>{p.sourceUrl ? <video controls playsInline preload="metadata" src={p.sourceUrl} className="max-h-[550px] w-full rounded-xl bg-[#10202b]" aria-label="Original reference ad"/> : <p className="rounded-xl border border-border p-6 text-sm">Reference preview unavailable. Refresh to renew the private link.</p>}</div><div><h2 className="mb-3 font-semibold">Your remake</h2>{p.videoUrl ? <video controls playsInline preload="metadata" src={p.videoUrl} className="max-h-[550px] w-full rounded-xl bg-[#10202b]" aria-label="AI-edited product ad"/> : <div className="grid min-h-48 place-items-center rounded-xl border border-dashed border-border p-6 text-sm text-muted-foreground">{active ? "Your remake is being prepared." : p.status === "complete" ? "Refresh to renew the private export link." : "Review your brief, then render."}</div>}</div></section>
      <section className="rounded-2xl border border-border bg-card p-6"><h2 className="font-semibold">{p.brief.productName}</h2><div className="mt-4 grid grid-cols-4 gap-3">{p.productUrls.map((url, i) => <div key={url} className="relative aspect-square overflow-hidden rounded-xl bg-accent"><Image src={url} alt={`Original product reference ${i + 1}`} fill unoptimized className="object-contain"/></div>)}</div><h3 className="mt-6 text-sm font-semibold">Approved edit instructions</h3><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-7 text-muted-foreground">{p.brief.instructions}</p>{p.brief.cta ? <p className="mt-4 text-sm">Closing CTA: {p.brief.cta}</p> : null}</section>
    </div><aside className="space-y-5"><section className="rounded-2xl border border-border bg-card p-6"><h2 className="font-semibold">Your export</h2><p className="mt-4 text-sm leading-7">{adRemakeModels[p.brief.model].name}<br/>{p.brief.seconds}s billed duration · original aspect ratio<br/>{p.brief.keepAudio ? "Original audio retained when present" : "Silent export"}<br/>Private MP4 · visible AI-edited disclosure</p></section>
      {error || p.error ? <p role="alert" className="rounded-xl border border-destructive/30 p-4 text-sm text-destructive">{error || p.error}</p> : null}
      {active ? <div role="status" className="rounded-xl bg-accent p-5"><p className="font-semibold">{p.job?.cancelRequested ? "Cancelling…" : p.job?.phase || "Waiting for worker…"}</p><p className="mt-3 text-xs leading-6">You can leave and return. Submitted model requests are saved so reconnection does not submit another paid request.</p></div> : null}
      {p.status === "complete" ? <><Button className="w-full" disabled={!p.videoUrl} asChild={!!p.videoUrl}>{p.videoUrl ? <a href={p.videoUrl} download="ad-remake.mp4" target="_blank" rel="noopener noreferrer">Open / download MP4</a> : <span>Export link unavailable</span>}</Button><Button className="w-full" variant="outline" onClick={() => router.refresh()}>Refresh private links</Button></> : <><p className="text-sm leading-6">Render cost: <strong>{adRemakeCredits(p.brief)} credits</strong>. Failed or cancelled renders return reserved credits.</p>{!active ? <label className="flex gap-3 text-xs leading-6"><input type="checkbox" checked={approved} onChange={e => setApproved(e.target.checked)} className="mt-1 size-4 shrink-0 accent-primary"/>I approve these inputs, edit instructions, rights and the displayed credit cost.</label> : null}<Button className="w-full" disabled={pending || (!active && !approved) || (active && (p.job?.status !== "reserved" || p.job.cancelRequested))} onClick={() => startTransition(async () => { setError(null); try { const result = await startAdRemakeJob(p.id, approved || active); if (result.error) setError(result.error); router.refresh(); } catch { setError("Connection interrupted. Refresh before retrying; your saved job is preserved."); } })}>{pending ? "Connecting…" : active ? "Reconnect saved job" : "Confirm & remake ad"}</Button></>}
      {active && p.job ? <CancelJobButton jobId={p.job.id} title={p.title} requested={p.job.cancelRequested} onUpdate={() => router.refresh()}/> : null}
      <Button asChild variant="outline" className="w-full"><Link href="/studio/ad-remake">Create another remake</Link></Button><p className="text-xs leading-6 text-muted-foreground">Compare product details, text and claims with your originals before sharing. Nothing is published automatically. Saved briefs are locked; create a new project to change the inputs or model.</p>
    </aside></div>
  </main>;
}
