"use client";

import Link from "next/link";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, FileText, Lightbulb, LoaderCircle, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { SceneArt } from "@/components/marketing/scene-art";
import { defaultBrief, briefSchema, type FacelessBrief } from "@/lib/faceless/schema";
import { createFacelessProject } from "@/app/studio/faceless/actions";

export function OptionField({label,value,options,onChange}:{label:string;value:string;options:{value:string;label:string}[];onChange:(v:string)=>void}) {
  return <div className="space-y-2"><Label>{label}</Label><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue /></SelectTrigger><SelectContent>{options.map((option)=><SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select></div>;
}
export function FacelessCreator({demo,projects}:{demo:boolean;projects:{id:string;title:string;status:string}[]}) {
  const router=useRouter(); const [brief,setBrief]=useState<FacelessBrief>(defaultBrief); const [pending,startTransition]=useTransition(); const [error,setError]=useState("");
  function update<K extends keyof FacelessBrief>(key:K,value:FacelessBrief[K]) {setBrief((old)=>({...old,[key]:value}));}
  function submit(e:React.FormEvent) {e.preventDefault();setError("");const parsed=briefSchema.safeParse(brief);if(!parsed.success){setError("Add an idea or script of at least 12 characters.");return;}startTransition(async()=>{try{const result=await createFacelessProject(parsed.data);if(result.error)setError(result.error);else if(result.id)router.push(`/studio/faceless/${result.id}`);}catch{setError("Unable to save. Check your connection and try again.");}});}
  return <main className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><div className="flex items-center gap-2 text-primary"><Sparkles className="size-4" /><p className="eyebrow">An idea is all it takes</p></div><h1 className="editorial mt-3 text-4xl sm:text-5xl">Faceless video generator</h1><p className="mt-4 max-w-2xl leading-7 text-muted-foreground">Big on story. No face required. Turn any topic into a short video with AI images, narration, and captions.</p>
    {demo && <div className="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-primary/20 bg-accent/50 p-4 text-sm"><p>Explore the sample editor. Real generation requires a signed-in account and connected providers.</p><Button asChild size="sm" variant="outline"><Link href="/studio/faceless/demo">Open sample storyboard <ArrowRight /></Link></Button></div>}
    <div className="mt-8 grid gap-8 lg:grid-cols-[1fr_320px]"><Card className="p-6 sm:p-8"><form onSubmit={submit} className="space-y-7"><div className="flex gap-2 border-b border-border pb-5">{([{mode:"idea",label:"Start with an idea",icon:Lightbulb},{mode:"script",label:"Use my own script",icon:FileText}] as const).map(({mode,label,icon:Icon})=><Button key={mode} type="button" variant={brief.mode===mode ? "default":"ghost"} onClick={()=>update("mode",mode)}><Icon />{label}</Button>)}</div>
      <div className="space-y-3"><Label htmlFor="video-topic">{brief.mode==="idea" ? "What’s your video about?":"Your narration script"}</Label><Textarea id="video-topic" className="min-h-36 resize-y text-base" required minLength={12} maxLength={1800} value={brief.topic} onChange={(e)=>update("topic",e.target.value)} placeholder={brief.mode==="idea" ? "For example: Why the night sky is a time machine. Make it intriguing and easy to understand.":"Paste your narration here. We’ll divide it into editable scenes without rewriting your words."} /><p className="text-xs text-muted-foreground">{brief.mode==="idea" ? "AI script: 2 credits. You’ll review and edit it before rendering.":"Your own script: no AI writing charge. Keep it under 80 words for 30 seconds, or 155 for 60 seconds."}</p></div>
      <div className="grid grid-cols-2 gap-5"><OptionField label="Target length" value={String(brief.duration)} options={[{value:"30",label:"~30 seconds"},{value:"60",label:"~60 seconds"}]} onChange={(v)=>update("duration",Number(v) as 30|60)} /><OptionField label="Video format" value={brief.aspectRatio} options={[{value:"9:16",label:"9:16 · Shorts & Reels"},{value:"16:9",label:"16:9 · Landscape"}]} onChange={(v)=>update("aspectRatio",v as FacelessBrief["aspectRatio"])} /><OptionField label="Visual style" value={brief.style} options={["Cinematic","Illustration","Watercolor"].map((v)=>({value:v,label:v}))} onChange={(v)=>update("style",v as FacelessBrief["style"])} /><OptionField label="Story tone" value={brief.tone} options={["Informative","Storytelling","Inspiring"].map((v)=>({value:v,label:v}))} onChange={(v)=>update("tone",v as FacelessBrief["tone"])} /><OptionField label="Narration language" value={brief.language} options={[{value:"en",label:"English"},{value:"es",label:"Spanish"},{value:"fr",label:"French"}]} onChange={(v)=>update("language",v as FacelessBrief["language"])} /><div className="flex items-center justify-between gap-3 rounded-lg border border-border px-3"><Label htmlFor="captions">Timed captions</Label><Switch id="captions" checked={brief.captions} onCheckedChange={(v)=>update("captions",v)} /></div></div>
      {error && <p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex flex-wrap items-center justify-between gap-4 border-t border-border pt-5"><p className="text-xs text-muted-foreground">Review first. Render when you’re ready.</p><Button type="submit" disabled={pending || demo}>{pending ? <LoaderCircle className="animate-spin" />:<ArrowRight />} Create project</Button></div>{demo && <p className="text-sm text-muted-foreground"><Link className="text-primary underline" href="/login?next=/studio/faceless">Sign in</Link> to create your own saved project.</p>}
    </form></Card><aside><div className="mx-auto h-[410px] w-[230px] overflow-hidden rounded-2xl border-[5px] border-card shadow-xl"><div className="relative h-full"><SceneArt variant="space" /><span className="absolute left-4 top-4 text-[10px] uppercase tracking-[.2em] text-white/80">Your next story</span><p className="absolute bottom-20 left-5 right-5 text-center font-serif text-3xl italic text-white">A little closer<br />to the stars.</p><span className="absolute bottom-5 inset-x-5 text-center text-[10px] text-white/70">Illustrative layout · not a generated video</span></div></div><div className="mt-6 space-y-3 px-4 text-xs leading-5 text-muted-foreground"><p><strong className="text-foreground">One complete workflow.</strong> Script → scene images → narration → captions → MP4.</p><p>Uses AI-generated still images with narrated scenes. No avatar, stock library, background music, or social auto-posting in this version.</p><p>Render: 20 credits. Voice uses your studio’s configured ElevenLabs voice.</p></div></aside></div>
    {projects.length>0 && <section className="mt-12"><h2 className="text-xl font-semibold">Your recent faceless videos</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{projects.map((p)=><Link key={p.id} href={`/studio/faceless/${p.id}`} className="rounded-xl border border-border bg-card p-5 transition-colors hover:border-primary"><p className="font-medium">{p.title}</p><p className="mt-2 text-xs capitalize text-muted-foreground">{p.status}</p></Link>)}</div></section>}
  </main>;
}
