"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { CancelJobButton } from "./cancel-job-button";
import { startEstateJob } from "@/app/studio/real-estate/actions";
import { estateCredits, estateModels, estateSeconds, type EstateProject } from "@/lib/real-estate/schema";

export function RealEstateProject({ project: p }: { project: EstateProject }) {
  const router = useRouter(), [pending, startTransition] = useTransition(), [error, setError] = useState<string | null>(null), [approved, setApproved] = useState(false);
  const active = p.status === "rendering";
  useEffect(() => { if (!active) return; const timer = setInterval(() => { if (!document.hidden) router.refresh(); }, 6000); return () => clearInterval(timer); }, [active, router]);
  return <div className="mx-auto max-w-6xl px-4 py-10 sm:px-8"><Link href="/studio/real-estate" className="text-sm text-primary">← Your listing studio</Link><p className="eyebrow mt-8 text-primary">Real estate / Review & render</p><h1 className="editorial mt-3 text-4xl">{p.title}</h1><div className="mt-8 grid gap-7 lg:grid-cols-[1fr_340px]"><div>
    {p.videoUrl && <div className="mb-7 overflow-hidden rounded-2xl bg-[#101c22]"><video controls playsInline preload="metadata" src={p.videoUrl} className="max-h-[650px] w-full" aria-label="Generated property listing tour"/></div>}
    <h2 className="text-lg font-semibold">Original photos & approved room sequence</h2><p className="mt-2 text-sm text-muted-foreground">Compare the finished video with these originals before you publish.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{p.brief.rooms.map((r, i) => { const photo = p.photos.find(a => a.id === r.assetId); return <div key={r.assetId} className="overflow-hidden rounded-2xl border border-border bg-card"><div className="relative aspect-video bg-accent">{photo?.url ? <Image src={photo.url} alt={`Original property photo: ${r.label}`} fill unoptimized className="object-contain"/> : <p className="p-5 text-sm">Original unavailable</p>}</div><div className="p-4"><p className="font-medium">{i + 1}. {r.label}</p><p className="mt-2 text-xs leading-6 text-muted-foreground">{r.narration || "No narration"}</p><p className="mt-2 text-xs text-muted-foreground">{r.motion} · {p.brief.secondsPerRoom}s</p></div></div>; })}</div>
    </div><aside className="space-y-5"><section className="rounded-2xl border border-border bg-card p-6"><h2 className="font-semibold">Your listing export</h2><p className="mt-4 text-sm leading-7">{estateModels.find(m => m.id === p.brief.model)?.name}<br/>{estateSeconds(p.brief)} seconds · {p.brief.aspectRatio} · 1080p export<br/>{p.brief.voice === "none" ? "No voiceover" : `${p.brief.voice} · ElevenLabs v3`}</p><div className="mt-5 border-t border-border pt-4 text-sm leading-7"><p>{p.brief.address}</p><p>{p.brief.price}</p><p>{p.brief.agent}</p><p className="break-words">{p.brief.contact}</p><p>{p.brief.cta}</p></div></section>
    {(error || p.error) && <p role="alert" className="rounded-xl border border-destructive/30 p-4 text-sm text-destructive">{error || p.error}</p>}
    {active && <div role="status" className="rounded-xl bg-accent p-5"><p className="font-semibold">{p.job?.cancelRequested ? "Cancelling…" : p.job?.phase || "Waiting for worker…"}</p><p className="mt-3 text-xs leading-6">You can leave and return. Progress is saved room by room.</p></div>}
    {p.videoUrl ? <><Button asChild className="w-full"><a href={p.videoUrl} download="listing.mp4" target="_blank" rel="noopener noreferrer">Open / download MP4</a></Button>{p.captionsUrl && <a href={p.captionsUrl} download="captions.srt" className="block text-sm text-primary underline">Download room-timed captions (SRT)</a>}<p className="text-xs leading-6 text-muted-foreground">Preview links expire; refresh to renew. Check property geometry, factual accuracy and local disclosure requirements before sharing.</p></> : <><p className="text-sm">Render cost: <strong>{estateCredits(p.brief).toLocaleString()} credits</strong>. Failed or cancelled renders return reserved credits.</p>{!active && <label className="flex gap-3 text-xs leading-6"><input type="checkbox" checked={approved} onChange={e => setApproved(e.target.checked)} className="mt-1 size-4 shrink-0"/>I approve these facts, photos and the displayed credit cost.</label>}<Button className="w-full" disabled={pending || (!active && !approved) || (active && (p.job?.status !== "reserved" || p.job.cancelRequested))} onClick={() => startTransition(async () => { setError(null); try { const result = await startEstateJob(p.id, approved || active); if (result.error) setError(result.error); router.refresh(); } catch { setError("Could not connect. Refresh before retrying; your saved job is preserved."); } })}>{pending ? "Connecting…" : active ? "Reconnect saved job" : "Confirm & render listing"}</Button></>}
    {active && p.job && <CancelJobButton jobId={p.job.id} title={p.title} requested={p.job.cancelRequested} onUpdate={() => router.refresh()}/>}
    <Button asChild variant="outline" className="w-full"><Link href="/studio/real-estate">Create another listing</Link></Button><p className="text-xs leading-6 text-muted-foreground">The saved brief is locked so queued work cannot change underneath you. To change facts, photos or models, create a new listing. Nothing is published automatically.</p>
    </aside></div></div>;
}
